import java.awt.Color;
import java.awt.Graphics;
/*********************************************************************************
* Bullet.java
* 
* Bullets are generated by objects of type Spaceship
* Have fixed dx and dy which modify x and y in each call to move()
* 				
***********************************************************************************/

public class Bullet {

	// DATA:
	private static final int RADIUS = 2;
	private static final Color STANDARD_COLOR = Color.RED;
	private static final int ADDED_VELOCITY = 20; // divided into changes to deltaDx and deltaDy
												  // when bullet is launched
	private int x, y;		// Center of the Bullet
	private int dx, dy;		// Velocity - change to x and y
							//  when the the Bullet moves
	// METHODS:
	
	/**
	 * Generates an object of type Bullet
	 * 
	 * @param xIn		x coordinate of center
	 * @param yIn		y coordinate of center
	 * @param dxIn		x velocity
	 * @param dyIn		y velocity

	 */
	public Bullet (int xIn, int yIn, int dxIn, int dyIn)
	{
		x = xIn;
		y = yIn;
		dx = dxIn;
		dy = dyIn;
	}
	
	/**
	 * Move the bullet.  Add the velocity to its center.
	 */
	public void move()
	{
		x = x + dx;
		y = y + dy;
	}
	
	/**
	 * Draw the bullet.
	 * 
	 * @param g			Graphics object in which to draw
	 */
	public void draw(Graphics g)
	{
		g.setColor(STANDARD_COLOR);
		g.fillOval(x - RADIUS, y - RADIUS, 2 * RADIUS, 2 * RADIUS);

	}	
	
}
